# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    environment: release

    defaults:
      run:
        working-directory: src

    steps:
    - name: Checout LB.Utility
      uses: actions/checkout@v4
      
    - name: Checkout NetDocMD
      uses: actions/checkout@v4
      with:
        repository: melance/NetDocMD
        ref: main
        path: tools/NetDocMD
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        
    - name: Restore dependencies 
      run: dotnet restore LB.Utility.sln
      
    - name: Build
      run: dotnet build LB.Utility.sln --configuration Release --no-restore

    - name: Update README
      working-directory: ${{ github.workspace }}
      run: >
        dotnet run --project tools/NetDocMD/NetDocMD/NetDocMD.csproj --
        --xml src/LB.Utility/bin/Release/net10.0/LB.Utility.xml
        --readme README.md

    - name: Commit updated README
      if: github.ref == 'refs/head/main'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[hot]@users.noreply.github.com"
        git add README.md
        git diff --cached --guiet || git commit -m "Update README"
        git push
    
    - name: Set Version Variables
      run: |
        echo "PACKAGE_VERSION=1.0.${{github.run_number}}" >> $GITHUB_ENV
        echo "FILE_VERSION=1.0.0.${{github.run_number}}" >> $GITHUB_ENV
        echo "ASSEMBLY_VERSION=1.0.0.0" >> $GITHUB_ENV
        
    - name: Pack
      run: >
        dotnet pack LB.Utility/LB.Utility.csproj 
        -c Release 
        --no-build 
        -p:PackageVersion=${{ env.PACKAGE_VERSION }}
        -p:Version=${{env.PACKAGE_VERSION }}
        -p:AssemblyVersion=${{env.ASSEMBLY_VERSION}}
        -p:FileVersion=${{env.FILE_VERSION}}
        -o ./nupkg

    - name: Nuget login (OIDC → temp API key)
      uses: Nuget/login@v1
      id: login
      with:
        user: ${{secrets.NUGET_USER}}

    - name: Nuget Push
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
